site_name: 'iOS Code Signing'
site_description: 'Code signing is required for iOS apps when you are distributing your app to your testers or to the App Store.'
site_author: 'Bitrise'
site_url: 'https://bitrise-io.github.io/ioscodesigning'

repo_name: 'GitHub'
repo_url: 'https://github.com/bitrise-io/ioscodesigning'

copyright: 'The iOS Code Signing guide is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License.'

theme: 'material'

pages:
- Introduction: 'index.md'
- Generate code signing files: 'generate-code-signing-files.md'
- Exporting code signing files: 'exporting-code-signing-files.md'
- Code signing iOS frameworks: 'code-signing-ios-frameworks.md'

markdown_extensions:
  - admonition
  - toc(permalink=true)
  - footnotes

extra:
  social:
    - type: 'github'
      link: 'https://github.com/bitrise-io/ioscodesigning'
    - type: 'twitter'
      link: 'https://twitter.com/bitrise'

google_analytics:
  - 'UA-53276411-6'
  - 'auto'
